const url = {
'1111':{url:'http://www.cqcp.net/game/ssc/',name:'重庆时时彩'},
'1122':{url:'http://www.xjflcp.com/',name:'新疆时时彩'},
'1133':{url:'http://www.tjflcpw.com/',name:'天津时时彩'},
'1144':{url:'http://www.lottost.cn/index.html',name:'黑龙江时时彩'},
'1155':{url:'http://www.ynflcp.cn/',name:'云南时时彩'},
'2201':{url:'http://www.ahfc.gov.cn/',name:'安徽快三'},
'2202':{url:'http://www.fjcp.cn/',name:'福建快三'},
'2203':{url:'http://www.gsflcp.com/',name:'甘肃快三'},
'2204':{url:'http://www.gzfucai.cn/',name:'贵州快三'},
'2205':{url:'http://www.yzfcw.com/',name:'河北快三'},
'2206':{url:'http://www.hbfcw.gov.cn/',name:'湖北快三'},
'2207':{url:'http://www.jlfc.com.cn/',name:'吉林快三'},
'2208':{url:'http://www.jslottery.com/',name:'江苏快三'},
'2209':{url:'http://www.jxlottery.cn/',name:'江西快三'},
'2210':{url:'http://www.nmlottery.com.cn/',name:'内蒙古快三'},
'2211':{url:'http://www.bwlc.net/',name:'北京快三'},
'2212':{url:'http://www.swlc.sh.cn/',name:'上海快三'},
'2222':{url:'http://www.gxlottery.com/',name:'广西快三'},
'4401':{url:'http://www.gdfc.org.cn/',name:'广东11选5'},
'4402':{url:'http://www.swlc.sh.cn/',name:'上海11选5'},
'4403':{url:'http://www.ahfc.gov.cn/',name:'安徽11选5'},
'4404':{url:'http://www.jxlottery.cn/',name:'江西11选5'},
'4405':{url:'http://www.jlfc.com.cn/',name:'吉林11选5'},
'4406':{url:'http://www.gxlottery.com/',name:'广西11选5'},
'4421':{url:'http://www.hbfcw.gov.cn/',name:'湖北11选5'},
'4422':{url:'http://www.lnlotto.com/',name:'辽宁11选5'},
'4423':{url:'http://www.jslottery.com/',name:'江苏11选5'},
'4424':{url:'http://www.zjflcp.com/',name:'浙江11选5'},
'4425':{url:'http://www.nmlottery.com.cn/',name:'内蒙古11选5'},
'5501':{url:'http://www.bwlc.net/',name:'北京赛车'},
'6601':{url:'http://bet.hkjc.com/',name:'六合彩'}
}

export default url